# Generated by Django 5.0.14 on 2026-02-21 04:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('AB', 'AB'), ('EG', 'EG'), ('HJ', 'HJ'), ('CD', 'CD'), ('OTHER', 'Other')], default='OTHER', help_text='Physical area of the building.', max_length=10)),
                ('system', models.CharField(choices=[('INDUCT', 'Induct'), ('TSORT', 'TSORT'), ('ADTA', 'ADTA'), ('SBL', 'SBL'), ('OTHER', 'Other')], default='OTHER', help_text='System type or equipment category.', max_length=20)),
                ('asset_name', models.CharField(help_text='Human-readable asset name.', max_length=200)),
                ('asset_id', models.CharField(blank=True, help_text='Optional internal identifier.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor company name.', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('vendor', models.ForeignKey(help_text='Vendor company this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='visits.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short summary shown on calendar.', max_length=200)),
                ('start_dt', models.DateTimeField(help_text='Scheduled start date and time.')),
                ('end_dt', models.DateTimeField(help_text='Scheduled end date and time.')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', help_text='Current lifecycle state of the visit.', max_length=20)),
                ('work_scope', models.TextField(blank=True, help_text='Detailed description of work to be performed.')),
                ('sim_ticket', models.CharField(blank=True, help_text='Reference SIM ticket number.', max_length=100)),
                ('work_order', models.CharField(blank=True, help_text='Internal or vendor work order reference.', max_length=100)),
                ('pre_visit_notes', models.TextField(blank=True, help_text='Planning notes, access constraints, staging details.')),
                ('post_visit_handoff', models.TextField(blank=True, help_text='Summary for other technicians after completion.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Primary vendor contact for this visit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visits.vendorcontact')),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment involved in this visit.', related_name='visits', to='visits.equipment')),
                ('site_owner', models.ForeignKey(blank=True, help_text='Internal technician responsible for coordination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_visits', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Vendor company performing the work.', on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visits.vendor')),
            ],
            options={
                'ordering': ['-start_dt'],
            },
        ),
    ]
