# Generated by Django 5.2.11 on 2026-02-21 04:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='area',
            field=models.CharField(choices=[('AB', 'AB'), ('EG', 'EG'), ('HJ', 'HJ'), ('CD', 'CD'), ('BLDG', 'Building'), ('OTHER', 'Other')], default='OTHER', help_text='Physical area of the building where the equipment group is located.', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Optional structured identifier (example AB.ADTA.01).', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_name',
            field=models.CharField(help_text='Human-readable equipment group name used in UI and communication.', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='system',
            field=models.CharField(choices=[('INDUCT', 'Induct'), ('TSORT', 'TSORT'), ('ADTA', 'ADTA'), ('SBL', 'SBL'), ('MHE_OTHER', 'MHE Other'), ('HVAC', 'HVAC'), ('FANS', 'Fans'), ('FLS', 'Fire Life Safety'), ('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('BUILDING', 'Building'), ('OTHER', 'Other')], default='OTHER', help_text='System type or equipment category.', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional contact email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='name',
            field=models.CharField(help_text='Contact full name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorcontact',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional contact phone number.', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the visit record was created.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Equipment groups involved in this visit.', related_name='visits', to='visits.equipment'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='post_visit_handoff',
            field=models.TextField(blank=True, help_text='Summary for other technicians after completion including follow ups.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='pre_visit_notes',
            field=models.TextField(blank=True, help_text='Planning notes, access constraints, staging details, and prep items.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sim_ticket',
            field=models.CharField(blank=True, help_text='Reference SIM ticket number if applicable.', max_length=100),
        ),
        migrations.AlterField(
            model_name='visit',
            name='site_owner',
            field=models.ForeignKey(blank=True, help_text='Internal technician responsible for coordination and handoff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='title',
            field=models.CharField(help_text='Short summary shown on calendar (example Annual PM or Alignment check).', max_length=200),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the visit record was last updated.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='work_order',
            field=models.CharField(blank=True, help_text='Internal or vendor work order reference if applicable.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['area', 'system'], name='visits_equi_area_879c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_id'], name='visits_equi_asset_i_cc0f93_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['start_dt', 'end_dt'], name='visits_visi_start_d_120a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status'], name='visits_visi_status_ae8d13_idx'),
        ),
    ]
